'use client';

import { ClerkProvider } from '@clerk/nextjs';
import { enUS } from '@clerk/localizations';

const customLocalization = {
  ...enUS,
  // 기본 안내문
  backButton: '뒤로가기',
  socialButtonsBlockButton: '소셜 계정으로 계속하기',
  socialButtonsBlockButtonManyInView: '소셜 계정으로 계속하기',
  // 회원가입
  signUp: {
    ...((enUS.signUp as any) ?? {}),
    start: {
      ...((enUS.signUp?.start as any) ?? {}),
      title: '계정 만들기',
      subtitle: '아래 정보를 입력해 회원가입을 진행하세요.',
      actionText: '이미 계정이 있으신가요?',
      actionLink: '로그인',
    },
    emailCode: {
      ...((enUS.signUp?.emailCode as any) ?? {}),
      title: '이메일 인증',
      subtitle: '이메일로 전송된 인증 코드를 입력하세요.',
      formTitle: '인증 코드',
      formSubtitle: '이메일로 전송된 인증 코드를 입력하세요.',
      resendButton: '코드 재전송',
    },
    emailLink: {
      ...((enUS.signUp?.emailLink as any) ?? {}),
      title: '이메일 인증',
      subtitle: '이메일로 전송된 인증 링크를 사용하세요.',
      formTitle: '인증 링크',
      formSubtitle: '이메일로 전송된 인증 링크를 사용하세요.',
      resendButton: '링크 재전송',
      loading: { title: '가입 중...' },
      verified: { title: '가입 완료' },
      verifiedSwitchTab: {
        title: '이메일 인증 완료',
        subtitle: '새로 열린 탭으로 돌아가 계속 진행하세요.',
        subtitleNewTab: '이전 탭으로 돌아가 계속 진행하세요.',
      },
    },
    phoneCode: {
      ...((enUS.signUp?.phoneCode as any) ?? {}),
      title: '휴대폰 인증',
      subtitle: '휴대폰으로 전송된 인증 코드를 입력하세요.',
      formTitle: '인증 코드',
      formSubtitle: '휴대폰으로 전송된 인증 코드를 입력하세요.',
      resendButton: '코드 재전송',
    },
    continue: {
      ...((enUS.signUp?.continue as any) ?? {}),
      title: '추가 정보 입력',
      subtitle: '계속하려면 추가 정보를 입력하세요.',
      actionText: '이미 계정이 있으신가요?',
      actionLink: '로그인',
    },
    restrictedAccess: {
      ...((enUS.signUp?.restrictedAccess as any) ?? {}),
      title: '접근 제한',
      subtitle: '현재 회원가입이 제한되어 있습니다. 문의가 필요하면 지원팀에 연락하세요.',
      actionText: '이미 계정이 있으신가요?',
      actionLink: '로그인',
      blockButton__emailSupport: '이메일 지원',
      blockButton__joinWaitlist: '웨이팅리스트 등록',
      subtitleWaitlist: '웨이팅리스트에 등록하시면 출시 시 안내해드립니다.',
    },
    legalConsent: {
      ...((enUS.signUp?.legalConsent as any) ?? {}),
      continue: {
        ...((enUS.signUp?.legalConsent?.continue as any) ?? {}),
        title: '약관 동의',
        subtitle: '계속하려면 약관에 동의해 주세요.',
      },
      checkbox: {
        ...((enUS.signUp?.legalConsent?.checkbox as any) ?? {}),
        label__onlyPrivacyPolicy: '개인정보 처리방침에 동의합니다.',
        label__onlyTermsOfService: '이용약관에 동의합니다.',
        label__termsOfServiceAndPrivacyPolicy: '이용약관 및 개인정보 처리방침에 동의합니다.',
      },
    },
  },
  // 로그인
  signIn: {
    ...((enUS.signIn as any) ?? {}),
    start: {
      ...((enUS.signIn?.start as any) ?? {}),
      title: '로그인',
      subtitle: '이메일과 비밀번호로 로그인하세요.',
      actionText: '계정이 없으신가요?',
      actionLink: '회원가입',
    },
    alternativeMethods: {
      ...((enUS.signIn?.alternativeMethods as any) ?? {}),
      title: '다른 방법으로 로그인',
      subtitle: '아래 방법 중 하나로 로그인할 수 있습니다.',
      blockButton__emailLink: '이메일로 계속하기',
      blockButton__emailCode: '이메일 코드로 계속하기',
      blockButton__phoneCode: '휴대폰 코드로 계속하기',
      blockButton__password: '비밀번호로 계속하기',
      blockButton__passkey: '패스키로 계속하기',
      blockButton__totp: 'OTP로 계속하기',
      blockButton__backupCode: '백업 코드로 계속하기',
      actionText: '문제가 있으신가요?',
      actionLink: '도움 받기',
      getHelp: {
        ...((enUS.signIn?.alternativeMethods?.getHelp as any) ?? {}),
        title: '도움 받기',
        content: '로그인에 문제가 있으시면 지원팀에 이메일을 보내주세요.',
        blockButton__emailSupport: '이메일 지원',
      },
    },
    password: {
      ...((enUS.signIn?.password as any) ?? {}),
      title: '비밀번호 입력',
      subtitle: '계정의 비밀번호를 입력하세요.',
      actionLink: '다른 방법 사용',
    },
    forgotPassword: {
      ...((enUS.signIn?.forgotPassword as any) ?? {}),
      title: '비밀번호 재설정',
      subtitle: '비밀번호를 재설정하려면 아래 정보를 입력하세요.',
      subtitle_email: '먼저 이메일로 전송된 코드를 입력하세요.',
      subtitle_phone: '먼저 휴대폰으로 전송된 코드를 입력하세요.',
      formTitle: '재설정 코드',
      resendButton: '코드 재전송',
    },
    resetPassword: {
      ...((enUS.signIn?.resetPassword as any) ?? {}),
      title: '새 비밀번호 설정',
      formButtonPrimary: '비밀번호 재설정',
      requiredMessage: '보안을 위해 비밀번호 재설정이 필요합니다.',
      successMessage: '비밀번호가 성공적으로 변경되었습니다. 잠시 후 로그인됩니다.',
    },
    noAvailableMethods: {
      ...((enUS.signIn?.noAvailableMethods as any) ?? {}),
      title: '로그인 불가',
      subtitle: '사용 가능한 인증 방법이 없습니다.',
      message: '로그인을 진행할 수 없습니다.',
    },
    passkey: {
      ...((enUS.signIn?.passkey as any) ?? {}),
      title: '패스키 사용',
      subtitle: '패스키로 본인 인증을 진행합니다.',
    },
    backupCodeMfa: {
      ...((enUS.signIn?.backupCodeMfa as any) ?? {}),
      title: '백업 코드 입력',
      subtitle: '2단계 인증 시 받은 백업 코드를 입력하세요.',
    },
    emailCode: {
      ...((enUS.signIn?.emailCode as any) ?? {}),
      title: '이메일 인증',
      subtitle: '이메일로 전송된 인증 코드를 입력하세요.',
      formTitle: '인증 코드',
      resendButton: '코드 재전송',
    },
    emailLink: {
      ...((enUS.signIn?.emailLink as any) ?? {}),
      title: '이메일 인증',
      subtitle: '이메일로 전송된 인증 링크를 사용하세요.',
      formTitle: '인증 링크',
      resendButton: '링크 재전송',
      loading: { title: '로그인 중...' },
      verified: { title: '로그인 완료' },
      verifiedSwitchTab: {
        title: '이메일 인증 완료',
        subtitle: '새로 열린 탭으로 돌아가 계속 진행하세요.',
        subtitleNewTab: '이전 탭으로 돌아가 계속 진행하세요.',
      },
    },
    phoneCode: {
      ...((enUS.signIn?.phoneCode as any) ?? {}),
      title: '휴대폰 인증',
      subtitle: '휴대폰으로 전송된 인증 코드를 입력하세요.',
      formTitle: '인증 코드',
      resendButton: '코드 재전송',
    },
    resetPasswordMfa: {
      ...((enUS.signIn?.resetPasswordMfa as any) ?? {}),
      detailsLabel: '비밀번호 재설정 전 본인 인증이 필요합니다.',
    },
  },
  // 필드 라벨/placeholder/버튼 등 추가 한글화
  formFieldLabel__username: '아이디',
  formFieldInput__username: '아이디를 입력하세요',
  formFieldHint__username: '아이디는 영문, 숫자 조합으로 입력하세요.',
  formFieldError__username_require_non_number_character: '아이디에는 숫자가 아닌 문자가 1개 이상 포함되어야 합니다.',
  formFieldError__username_invalid_format: '아이디는 영문, 숫자 조합으로 입력하세요.',
  formFieldLabel__emailAddress: '이메일 주소',
  formFieldInput__emailAddress: '이메일을 입력하세요',
  formFieldHint__emailAddress: '유효한 이메일 주소를 입력하세요.',
  formFieldError__emailAddress_invalid_format: '유효한 이메일 주소를 입력하세요.',
  formFieldLabel__password: '비밀번호',
  formFieldInput__password: '비밀번호를 입력하세요',
  formFieldHint__password: '비밀번호는 8자 이상, 영문, 숫자, 특수문자를 포함해야 합니다.',
  formFieldError__password_invalid_format: '비밀번호는 8자 이상, 영문, 숫자, 특수문자를 포함해야 합니다.',
  formFieldError__password_length_too_short: '비밀번호는 8자 이상이어야 합니다.',
  formFieldError__password_not_strong_enough: '비밀번호가 충분히 강력하지 않습니다.',
  formFieldError__password_pwned: '이 비밀번호는 이미 유출된 적이 있습니다. 다른 비밀번호를 사용해 주세요.',
  formFieldError__required: '필수 입력 항목입니다.',
  formFieldError__generic: '입력값이 올바르지 않습니다. 다시 확인해 주세요.',
  formFieldHint__firstName: '이름을 입력하세요.',
  formFieldHint__lastName: '성을 입력하세요.',
  formFieldHint__phoneNumber: '휴대폰 번호를 입력하세요.',
  formButtonPrimary__continue: '계속',
  formButtonPrimary__signIn: '로그인',
  formButtonPrimary__signUp: '회원가입',
  formButtonPrimary__resetPassword: '비밀번호 재설정',
  formButtonPrimary__verify: '인증',
  formButtonPrimary__finish: '완료',
  formButtonReset: '취소',
  // 하단 안내/링크
  footerActionText__signIn: '이미 계정이 있으신가요?',
  footerActionLink__signIn: '로그인',
  footerActionText__signUp: '계정이 없으신가요?',
  footerActionLink__signUp: '회원가입',
  // 비밀번호 관련 에러 및 안내
  unstable__errors: {
    ...enUS.unstable__errors,
    form_password_pwned: '이 비밀번호는 이미 유출된 적이 있습니다. 다른 비밀번호를 사용해 주세요.',
    form_password_length_too_short: '비밀번호는 8자 이상이어야 합니다.',
    form_password_not_strong_enough: '비밀번호가 충분히 강력하지 않습니다.',
    form_password_validation_failed: '비밀번호가 올바르지 않습니다.',
    form_password_size_in_bytes_exceeded: '비밀번호가 허용되는 최대 바이트 수를 초과했습니다. 비밀번호를 줄이거나 일부 특수문자를 제거해 주세요.',
    passwordComplexity: {
      maximumLength: '{{length}}자 이하',
      minimumLength: '{{length}}자 이상',
      requireLowercase: '소문자',
      requireNumbers: '숫자',
      requireSpecialCharacter: '특수문자',
      requireUppercase: '대문자',
      sentencePrefix: '비밀번호는 다음을 포함해야 합니다'
    },
    zxcvbn: {
      couldBeStronger: '비밀번호는 작동하지만 더 강력할 수 있습니다. 문자를 더 추가해보세요.',
      goodPassword: '비밀번호가 모든 필요 요구사항을 충족합니다.',
      notEnough: '비밀번호가 충분히 강력하지 않습니다.',
      suggestions: {
        allUppercase: '모든 문자가 아닌 일부 문자를 대문자로 표시하세요.',
        anotherWord: '덜 일반적인 단어를 더 추가하세요.',
        associatedYears: '자신과 관련된 연도는 피하세요.',
        capitalization: '첫 글자 이상을 대문자로 표기하세요.',
        dates: '자신과 관련된 날짜와 연도는 피하세요.',
        l33t: "'a'에서 '@'와 같이 예측 가능한 문자 대체를 피하세요.",
        longerKeyboardPattern: '더 긴 키보드 패턴을 사용하고 타이핑 방향을 여러 번 변경하세요.',
        noNeed: '기호, 숫자 또는 대문자를 사용하지 않고도 강력한 비밀번호를 만들 수 있습니다.',
        pwned: '이 비밀번호를 다른 곳에서 사용한다면 변경해야 합니다.',
        recentYears: '최근 연도는 피하세요.',
        repeated: '반복되는 단어와 문자를 피하세요.',
        reverseWords: '일반적인 단어의 철자를 거꾸로 쓰지 마세요.',
        sequences: '일반적인 문자 시퀀스를 피하세요.',
        useWords: '여러 단어를 사용하되 일반적인 구문은 피하세요.'
      },
      warnings: {
        common: '일반적으로 사용되는 비밀번호입니다.',
        commonNames: '일반적인 이름과 성은 추측하기 쉽습니다.',
        dates: '날짜는 추측하기 쉽습니다.',
        extendedRepeat: '"abcabcabc"와 같이 반복되는 문자 패턴은 추측하기 쉽습니다.',
        keyPattern: '짧은 키보드 패턴은 추측하기 쉽습니다.',
        namesByThemselves: '단일 이름이나 성은 추측하기 쉽습니다.',
        pwned: '인터넷에서 데이터 유출로 인해 비밀번호가 노출되었습니다.',
        recentYears: '최근 연도는 추측하기 쉽습니다.',
        sequences: '"abc"와 같은 일반적인 문자 시퀀스는 추측하기 쉽습니다.',
        similarToCommon: '일반적으로 사용되는 비밀번호와 유사합니다.',
        simpleRepeat: '"aaa"와 같이 반복되는 문자는 추측하기 쉽습니다.',
        straightRow: '키보드의 같은 줄에 위치한 키를 사용하는 것은 추측하기 쉽습니다.',
        topHundred: '자주 사용되는 비밀번호입니다.',
        topTen: '아주 많이 사용되는 비밀번호입니다.',
        userInputs: '개인 정보나 페이지 관련 데이터가 없어야 합니다.',
        wordByItself: '한 단어는 추측하기 쉽습니다.'
      }
    }
  },
  // 기타 UI
  badge__activePlan: '활성',
  badge__canceledEndsAt: '취소됨 · 종료일: {{ date }}',
  badge__currentPlan: '현재 플랜',
  badge__default: '기본값',
  badge__expired: '만료됨',
  badge__primary: '기본',
  badge__renewsAt: '갱신일: {{ date }}',
  badge__requiresAction: '조치 필요',
  badge__startsAt: '시작일: {{ date }}',
  badge__thisDevice: '이 기기',
  badge__unverified: '미인증',
  badge__upcomingPlan: '예정 플랜',
  badge__userDevice: '사용자 기기',
  badge__you: '나',
};

export default function ClerkAppearanceProvider({ children }: { children: React.ReactNode }) {
  return <ClerkProvider>{children}</ClerkProvider>;
} 